/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-dragon-balls-77baebec10d940f08d09b5f9059d4066
Title: The Dragon Balls
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const DragonBalls = (props)=> {
  const { nodes, materials } = useGLTF('/models/dragon_balls.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['One_Star_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['One_Star_03_-_Default_0'].geometry}
          material={materials['03_-_Default']}
        />
      </group>
      <group position={[104.947, 0, 162.107]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[-194.573, 249.782, -144.212]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Four_Star_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Four_Star_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
      <group position={[-84.64, 0, 159.077]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[141.755, 245.126, -141.524]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Two_Star_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Two_Star_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
      <group position={[-167.507, 0, -1.834]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[288.76, -2.085, 1.204]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Five_Star_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Five_Star_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
      <group position={[-100.896, 0, -162.107]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[170.593, -248.318, 143.366]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Seven_Star_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Seven_Star_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
      <group position={[102.116, 0, -157.756]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[-189.55, -241.634, 139.507]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Star_Three_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Star_Three_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
      <group position={[167.507, 0, -2.487]} rotation={[-Math.PI / 3, 0, 0]} scale={0.564}>
        <group position={[-305.555, -3.089, 1.783]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Six_Star_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Six_Star_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/dragon_balls.glb')


export default DragonBalls
