/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Antouss (https://sketchfab.com/antouss)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/son-goku-and-kintoun-nimbus-0e05229282e644ab978d7d9c09ab4ec2
Title: Son Goku and Kintoun Nimbus
*/

import { Float,useGLTF } from '@react-three/drei'

const KidGoku = (props) => {
  const { nodes, materials } = useGLTF('/models/kid_goku.glb')
  return (
    <Float floatIntensity={1} speed={1} rotationIntensity={1}>
        <group {...props} dispose={null}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials['7_-nimbus_0_0_0']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials['7_-staffhand_0.1_16_16']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials['7_head_0.1_16_16']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials['7_body_0.1_16_16']}
            />
          </group>
        </group>
    </Float>
  )
}

useGLTF.preload('/models/kid_goku.glb')

export default KidGoku